---
name: Decision Record
about: Proposals for decision record creation.
title: ''
labels: ''
assignees: ''

---

Please describe your architectural change proposal using the following prompts. Erase this message and any 
unused optional prompts.

## Required

**Which project area is this ADR for?**

Please list the main project area this relates to...need to come up with list.

- frontend applications
- backend applications
- devops
- system design

**Which other ADRs does this proposal involve?**

Please list all of the other ADRs this proposal relates to.

**List where documentation needs to change if the ADR is accepted**

Surely some project documentation will need to change with most ADR changes.
